cabal update before install

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -38,7 +38,7 @@ script: |
   sudo aptitude update
   sudo aptitude full-upgrade -y
   sudo aptitude install -y bash wget coreutils tar xz-utils make libgmp-dev gzip curl zlib1g-dev
-  sudo aptitude install -y freeglut3-dev libblas-dev libbz2-dev libcairo2-dev libglib2.0-dev libgsl0-dev libicu-dev liblapack-dev libmysqlclient-dev libncurses5-dev libpango1.0-dev libpcre3-dev libpq-dev libtinfo-dev libxrandr-dev libxss-dev libzmq3-dev llvm llvm-dev nettle-dev opt pkg-config
+  sudo aptitude install -y freeglut3-dev libblas-dev libbz2-dev libcairo2-dev libglib2.0-dev libgsl0-dev libicu-dev liblapack-dev libmysqlclient-dev libncurses5-dev libpango1.0-dev libpcre3-dev libpq-dev libtinfo-dev libxrandr-dev libxss-dev libzmq3-dev llvm llvm-dev nettle-dev opt pkg-config libcurl4-openssl-dev libfreenect-dev libgd-dev libgtk2.0-dev libgtk-3-dev liblzma-dev libnotify-dev
   
   
   echo -e "\033[1m###  Installing GHC...  ######################################################\033[m"
@@ -47,7 +47,7 @@ script: |
   wget "${GHC_SOURCE}/${GHC_VER}/${GHC_TAR}"
   wget "${GHC_SOURCE}/${GHC_VER}/SHA256SUMS"
   CHECK=$(sha256sum -c SHA256SUMS 2>&1 | grep "${GHC_TAR}: ")
-  if [ "${CHECK}" != "${GHC_TAR}: OK" ]; then echo -e "\033[1mChecksum of\033[m ${GHC_TAR} \033[1mfailed!\033[m" ; exit 1 ; else echo -e "\033[1mChecksum of\033[m ${GHC_TAR} \033[1mOK.\033[m" ; fi
+  if [ "${CHECK}" != "${GHC_TAR}: OK" ]; then echo -e "\033[1mChecksum of\033[m ${GHC_TAR} \033[1mfailed.\033[m" ; exit 1 ; else echo -e "\033[1mChecksum of\033[m ${GHC_TAR} \033[1mOK.\033[m" ; fi
   tar xf $GHC_TAR
   cd ghc-${GHC_VER}
   echo -e "\033[1mConfiguring GHC\033[m"
@@ -82,7 +82,8 @@ script: |
   echo
   
   
-  echo -e "\033[1m###  Installing packages in Haskell Platform  ################################\033[m"
+  echo -e "\033[1m###  Installing packages alex and happy  #####################################\033[m"
+  cabal update
   cabal install alex happy
   echo
   
